include(Catch)

add_executable(test_operator_aggregation Aggregation.cpp)
target_link_libraries(test_operator_aggregation Catch2::Catch2WithMain columnar_operator)

add_executable(test_operator_scan Scan.cpp)
target_link_libraries(test_operator_scan Catch2::Catch2WithMain columnar_operator)

add_executable(test_operator_count Count.cpp)
target_link_libraries(test_operator_count Catch2::Catch2WithMain columnar_operator)

add_executable(test_expressions_core ExpressionCore.cpp)
target_link_libraries(test_expressions_core Catch2::Catch2WithMain columnar_operator)

add_executable(test_expression Expression.cpp)
target_link_libraries(test_expression Catch2::Catch2WithMain columnar_operator)

add_executable(test_filter Filter.cpp)
target_link_libraries(test_filter Catch2::Catch2WithMain columnar_operator)

add_executable(test_gluing Gluing.cpp)
target_link_libraries(test_gluing Catch2::Catch2WithMain columnar_operator)

add_executable(test_sort Sort.cpp)
target_link_libraries(test_sort Catch2::Catch2WithMain columnar_operator)

catch_discover_tests(test_operator_aggregation)
catch_discover_tests(test_operator_scan)
catch_discover_tests(test_operator_count)
catch_discover_tests(test_expressions_core)
catch_discover_tests(test_expression)
catch_discover_tests(test_filter)
catch_discover_tests(test_gluing)
catch_discover_tests(test_sort)