set(CMAKE_CXX_COMPILE_COMMANDS ON)
set(CMAKE_CXX_STANDARD 23)
set(CMAKE_CXX_STANDARD_REQUIRED ON)
set(CMAKE_EXPORT_COMPILE_COMMANDS ON)

set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -Wall -Wextra -Werror -Wpedantic")
set(CMAKE_CXX_FLAGS_DEBUG "${CMAKE_CXX_FLAGS} -fsanitize=address -fsanitize=undefined -fno-omit-frame-pointer -g")
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS} -O3 -ffast-math -flto -march=native -DGOOGLE_STRIP_LOG=2")

set(ENABLE_PGO "OFF" CACHE STRING "PGO mode: OFF, GENERATE, or USE")

if(ENABLE_PGO STREQUAL "GENERATE")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fprofile-generate")
elseif(ENABLE_PGO STREQUAL "USE")
    set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} -fprofile-use -fprofile-correction")
endif()


find_program(CLANG_TIDY_EXE clang-tidy)
set(CMAKE_CXX_CLANG_TIDY ${CLANG_TIDY_EXE};)
if(CMAKE_CXX_CLANG_TIDY)
    set(CMAKE_CXX_STANDARD_INCLUDE_DIRECTORIES ${CMAKE_CXX_IMPLICIT_INCLUDE_DIRECTORIES})
endif()